### ISSUE TITLE
Change send responses to JSON with a property that is only the ID

### ISSUE THREAD

**Issue by jarushford** [jarushford/top-vinyl#22]

**Comment by kayleenovak** [comment]
We would like to contribute to this issue. Is there any additional information that you would like us to know regarding this issue?

**Comment by jarushford** [comment]
Sounds good, sorry if the issue description is kind of terrible now that I'm re-reading it haha... Took me a second to realize what I even meant. I have a handful of responses that use `send` to give back a message. The thought was to change them all to `json` and where applicable send back an object with a `message` (which is what is already there) and the `id` of the item in question. Thanks!

**Comment by colev1** [comment]
Got it, thanks for clarifying!
